"""Dictionary mapping stock tickers to biggest competitors within the same industry/sector."""

competitor_map = {
    'OMC': ['TTD'],
    'TTD': ['OMC'],
    'FOXA': ['PSKY'],
    'PSKY': ['FOXA'],
    'CHTR': ['ECHO'],
    'ECHO': ['CHTR'],
    'T': ['VZ', 'CMCSA'],
    'CMCSA': ['VZ', 'T'],
    'VZ': ['T', 'CMCSA'],
    'EA': ['TTWO'],
    'TTWO': ['EA'],
    'GOOGL': ['META'],
    'META': ['GOOGL'],
    'LYV': ['NFLX', 'DIS'],
    'NFLX': ['DIS', 'WBD'],
    'DIS': ['NFLX', 'WBD'],
    'TKO': ['NFLX', 'DIS'],
    'WBD': ['NFLX', 'DIS'],
    'NWSA': ['GOOGL', 'META'],
    'TMUS': ['GOOGL', 'META'],
    'ROST': ['TJX'],
    'TJX': ['ROST'],
    'LULU': ['TPR', 'RL'],
    'RL': ['TPR', 'LULU'],
    'TPR': ['RL', 'LULU'],
    'F': ['TSLA', 'GM'],
    'GM': ['TSLA', 'F'],
    'TSLA': ['F', 'GM'],
    'APTV': ['AMZN', 'TSLA'],
    'AZO': ['ORLY', 'CVNA'],
    'CVNA': ['ORLY', 'AZO'],
    'ORLY': ['AZO', 'CVNA'],
    'AMZN': ['EBAY'],
    'EBAY': ['AMZN'],
    'LVS': ['MGM', 'WYNN'],
    'MGM': ['LVS', 'WYNN'],
    'WYNN': ['LVS', 'MGM'],
    'BBY': ['AMZN', 'TSLA'],
    'GRMN': ['AMZN', 'TSLA'],
    'GPC': ['AMZN', 'TSLA'],
    'DECK': ['NKE'],
    'NKE': ['DECK'],
    'LOW': ['HD'],
    'HD': ['LOW'],
    'DHI': ['PHM', 'LEN'],
    'LEN': ['DHI', 'PHM'],
    'NVR': ['DHI', 'PHM'],
    'PHM': ['DHI', 'LEN'],
    'WSM': ['AMZN', 'TSLA'],
    'ABNB': ['BKNG', 'MAR'],
    'BKNG': ['MAR', 'RCL'],
    'CCL': ['BKNG', 'MAR'],
    'EXPE': ['BKNG', 'MAR'],
    'HLT': ['BKNG', 'MAR'],
    'MAR': ['BKNG', 'RCL'],
    'NCLH': ['BKNG', 'MAR'],
    'RCL': ['BKNG', 'MAR'],
    'HAS': ['AMZN', 'TSLA'],
    'TSCO': ['ULTA'],
    'ULTA': ['TSCO'],
    'CMG': ['MCD', 'SBUX'],
    'DRI': ['MCD', 'SBUX'],
    'DPZ': ['MCD', 'SBUX'],
    'DASH': ['MCD', 'SBUX'],
    'MCD': ['SBUX', 'DASH'],
    'SBUX': ['MCD', 'DASH'],
    'YUM': ['MCD', 'SBUX'],
    'ADM': ['BG'],
    'BG': ['ADM'],
    'TAP': ['WMT', 'COST'],
    'COST': ['WMT', 'TGT'],
    'DG': ['WMT', 'COST'],
    'DLTR': ['WMT', 'COST'],
    'TGT': ['WMT', 'COST'],
    'WMT': ['COST', 'TGT'],
    'BF.B': ['STZ'],
    'STZ': ['BF.B'],
    'SYY': ['WMT', 'COST'],
    'CASY': ['KR'],
    'KR': ['CASY'],
    'CHD': ['PG', 'CL'],
    'CL': ['PG', 'KMB'],
    'KMB': ['PG', 'CL'],
    'CLX': ['PG', 'CL'],
    'PG': ['CL', 'KMB'],
    'GIS': ['MDLZ', 'KHC'],
    'HRL': ['MDLZ', 'KHC'],
    'MKC': ['MDLZ', 'KHC'],
    'MDLZ': ['KHC', 'HSY'],
    'HSY': ['MDLZ', 'KHC'],
    'SJM': ['MDLZ', 'KHC'],
    'KHC': ['MDLZ', 'HSY'],
    'TSN': ['MDLZ', 'KHC'],
    'KVUE': ['EL'],
    'EL': ['KVUE'],
    'KDP': ['KO', 'PEP'],
    'MNST': ['KO', 'PEP'],
    'PEP': ['KO', 'MNST'],
    'KO': ['PEP', 'MNST'],
    'MO': ['PM'],
    'PM': ['MO'],
    'CVX': ['XOM', 'OXY'],
    'XOM': ['CVX', 'OXY'],
    'OXY': ['XOM', 'CVX'],
    'BKR': ['SLB', 'HAL'],
    'HAL': ['SLB', 'BKR'],
    'SLB': ['BKR', 'HAL'],
    'APA': ['COP', 'EOG'],
    'COP': ['EOG', 'FANG'],
    'DVN': ['COP', 'EOG'],
    'FANG': ['COP', 'EOG'],
    'EOG': ['COP', 'FANG'],
    'EQT': ['COP', 'EOG'],
    'EXE': ['COP', 'EOG'],
    'TPL': ['COP', 'EOG'],
    'MPC': ['PSX', 'VLO'],
    'PSX': ['MPC', 'VLO'],
    'VLO': ['MPC', 'PSX'],
    'KMI': ['WMB', 'OKE'],
    'OKE': ['WMB', 'KMI'],
    'TRGP': ['WMB', 'KMI'],
    'WMB': ['KMI', 'OKE'],
    'AMP': ['BLK', 'BNY'],
    'ARES': ['BLK', 'BNY'],
    'BLK': ['BNY', 'BX'],
    'BX': ['BLK', 'BNY'],
    'BEN': ['BLK', 'BNY'],
    'IVZ': ['BLK', 'BNY'],
    'KKR': ['BLK', 'BNY'],
    'NTRS': ['BLK', 'BNY'],
    'STT': ['BLK', 'BNY'],
    'TROW': ['BLK', 'BNY'],
    'BNY': ['BLK', 'BX'],
    'AXP': ['COF', 'SYF'],
    'COF': ['AXP', 'SYF'],
    'SYF': ['AXP', 'COF'],
    'BAC': ['JPM', 'WFC'],
    'C': ['JPM', 'BAC'],
    'FITB': ['JPM', 'BAC'],
    'JPM': ['BAC', 'WFC'],
    'KEY': ['JPM', 'BAC'],
    'PNC': ['JPM', 'BAC'],
    'USB': ['JPM', 'BAC'],
    'WFC': ['JPM', 'BAC'],
    'APO': ['JPM', 'BRK.A'],
    'CBOE': ['SPGI', 'ICE'],
    'CME': ['SPGI', 'ICE'],
    'COIN': ['SPGI', 'ICE'],
    'FDS': ['SPGI', 'ICE'],
    'ICE': ['SPGI', 'CME'],
    'MCO': ['SPGI', 'ICE'],
    'MSCI': ['SPGI', 'ICE'],
    'NDAQ': ['SPGI', 'ICE'],
    'SPGI': ['ICE', 'CME'],
    'AON': ['MMC', 'AJG'],
    'AJG': ['MMC', 'AON'],
    'BRO': ['MMC', 'AON'],
    'MMC': ['AON', 'AJG'],
    'WTW': ['MMC', 'AON'],
    'IBKR': ['MS', 'GS'],
    'MS': ['GS', 'SCHW'],
    'RJF': ['MS', 'GS'],
    'HOOD': ['MS', 'GS'],
    'SCHW': ['MS', 'GS'],
    'GS': ['MS', 'SCHW'],
    'AFL': ['MET', 'PRU'],
    'GL': ['MET', 'PRU'],
    'MET': ['PRU', 'AFL'],
    'PFG': ['MET', 'PRU'],
    'PRU': ['MET', 'AFL'],
    'BRK.A': ['JPM', 'V'],
    'AIG': ['CB', 'PGR'],
    'ACGL': ['CB', 'PGR'],
    'AIZ': ['CB', 'PGR'],
    'CB': ['PGR', 'TRV'],
    'CINF': ['CB', 'PGR'],
    'ERIE': ['CB', 'PGR'],
    'L': ['CB', 'PGR'],
    'ALL': ['CB', 'PGR'],
    'HIG': ['CB', 'PGR'],
    'PGR': ['CB', 'TRV'],
    'TRV': ['CB', 'PGR'],
    'WRB': ['CB', 'PGR'],
    'CFG': ['TFC', 'MTB'],
    'HBAN': ['TFC', 'MTB'],
    'MTB': ['TFC', 'HBAN'],
    'RF': ['TFC', 'MTB'],
    'TFC': ['MTB', 'HBAN'],
    'EG': ['JPM', 'BRK.A'],
    'XYZ': ['V', 'MA'],
    'CPAY': ['V', 'MA'],
    'FIS': ['V', 'MA'],
    'FISV': ['V', 'MA'],
    'GPN': ['V', 'MA'],
    'JKHY': ['V', 'MA'],
    'MA': ['V', 'FISV'],
    'PYPL': ['V', 'MA'],
    'V': ['MA', 'FISV'],
    'ABBV': ['AMGN', 'GILD'],
    'AMGN': ['ABBV', 'GILD'],
    'BIIB': ['ABBV', 'AMGN'],
    'GILD': ['ABBV', 'AMGN'],
    'INCY': ['ABBV', 'AMGN'],
    'MRNA': ['ABBV', 'AMGN'],
    'REGN': ['ABBV', 'AMGN'],
    'VRTX': ['ABBV', 'AMGN'],
    'CAH': ['MCK', 'COR'],
    'COR': ['MCK', 'CAH'],
    'HSIC': ['MCK', 'COR'],
    'MCK': ['COR', 'CAH'],
    'ABT': ['SYK', 'MDT'],
    'BAX': ['ABT', 'SYK'],
    'BDX': ['ABT', 'SYK'],
    'BSX': ['ABT', 'SYK'],
    'DXCM': ['ABT', 'SYK'],
    'EW': ['ABT', 'SYK'],
    'GEHC': ['ABT', 'SYK'],
    'IDXX': ['ABT', 'SYK'],
    'PODD': ['ABT', 'SYK'],
    'ISRG': ['ABT', 'SYK'],
    'MDT': ['ABT', 'SYK'],
    'RMD': ['ABT', 'SYK'],
    'STE': ['ABT', 'SYK'],
    'SYK': ['ABT', 'MDT'],
    'ZBH': ['ABT', 'SYK'],
    'HCA': ['UHS'],
    'UHS': ['HCA'],
    'CVS': ['CI', 'DGX'],
    'DVA': ['CVS', 'CI'],
    'LH': ['CVS', 'CI'],
    'DGX': ['CVS', 'CI'],
    'CI': ['CVS', 'DGX'],
    'ALGN': ['SOLV', 'COO'],
    'SOLV': ['COO', 'ALGN'],
    'COO': ['SOLV', 'ALGN'],
    'VEEV': ['LLY', 'JNJ'],
    'A': ['TMO', 'DHR'],
    'TECH': ['TMO', 'DHR'],
    'CRL': ['TMO', 'DHR'],
    'DHR': ['TMO', 'IQV'],
    'IQV': ['TMO', 'DHR'],
    'MTD': ['TMO', 'DHR'],
    'RVTY': ['TMO', 'DHR'],
    'TMO': ['DHR', 'IQV'],
    'WAT': ['TMO', 'DHR'],
    'WST': ['TMO', 'DHR'],
    'CNC': ['UNH', 'ELV'],
    'ELV': ['UNH', 'HUM'],
    'HUM': ['UNH', 'ELV'],
    'UNH': ['ELV', 'HUM'],
    'BMY': ['LLY', 'JNJ'],
    'LLY': ['JNJ', 'MRK'],
    'JNJ': ['LLY', 'MRK'],
    'MRK': ['LLY', 'JNJ'],
    'PFE': ['LLY', 'JNJ'],
    'VTRS': ['LLY', 'JNJ'],
    'ZTS': ['LLY', 'JNJ'],
    'AXON': ['GE', 'RTX'],
    'GD': ['GE', 'RTX'],
    'GE': ['RTX', 'BA'],
    'HONA': ['GE', 'RTX'],
    'HWM': ['GE', 'RTX'],
    'HII': ['GE', 'RTX'],
    'LHX': ['GE', 'RTX'],
    'LMT': ['GE', 'RTX'],
    'NOC': ['GE', 'RTX'],
    'RTX': ['GE', 'BA'],
    'TXT': ['GE', 'RTX'],
    'BA': ['GE', 'RTX'],
    'TDG': ['GE', 'RTX'],
    'DE': ['CAT', 'GE'],
    'CHRW': ['UPS', 'FDX'],
    'EXPD': ['UPS', 'FDX'],
    'FDX': ['UPS', 'CHRW'],
    'UPS': ['FDX', 'CHRW'],
    'AOS': ['TT', 'JCI'],
    'ALLE': ['TT', 'JCI'],
    'BLDR': ['TT', 'JCI'],
    'CARR': ['TT', 'JCI'],
    'JCI': ['TT', 'CARR'],
    'LII': ['TT', 'JCI'],
    'MAS': ['TT', 'JCI'],
    'TT': ['JCI', 'CARR'],
    'FDXF': ['ODFL', 'JBHT'],
    'JBHT': ['ODFL', 'FDXF'],
    'ODFL': ['JBHT', 'FDXF'],
    'FIX': ['PWR', 'EME'],
    'EME': ['PWR', 'FIX'],
    'PWR': ['FIX', 'EME'],
    'CAT': ['CMI', 'PCAR'],
    'CMI': ['CAT', 'PCAR'],
    'PCAR': ['CAT', 'CMI'],
    'WAB': ['CAT', 'CMI'],
    'BR': ['CAT', 'GE'],
    'CTAS': ['CPRT'],
    'CPRT': ['CTAS'],
    'AME': ['ETN', 'VRT'],
    'ETN': ['VRT', 'EMR'],
    'EMR': ['ETN', 'VRT'],
    'GNRC': ['ETN', 'VRT'],
    'HUBB': ['ETN', 'VRT'],
    'ROK': ['ETN', 'VRT'],
    'VRT': ['ETN', 'EMR'],
    'RSG': ['WM', 'VLTO'],
    'ROL': ['WM', 'RSG'],
    'VLTO': ['WM', 'RSG'],
    'WM': ['RSG', 'VLTO'],
    'GEV': ['CAT', 'GE'],
    'ADP': ['PAYX'],
    'PAYX': ['ADP'],
    'MMM': ['HON'],
    'HON': ['MMM'],
    'DOV': ['PH', 'ITW'],
    'FTV': ['PH', 'ITW'],
    'IEX': ['PH', 'ITW'],
    'ITW': ['PH', 'IR'],
    'IR': ['PH', 'ITW'],
    'NDSN': ['PH', 'ITW'],
    'OTIS': ['PH', 'ITW'],
    'PH': ['ITW', 'IR'],
    'PNR': ['PH', 'ITW'],
    'SNA': ['PH', 'ITW'],
    'SWK': ['PH', 'ITW'],
    'XYL': ['PH', 'ITW'],
    'DAL': ['UAL', 'LUV'],
    'LUV': ['DAL', 'UAL'],
    'UAL': ['DAL', 'LUV'],
    'UBER': ['CAT', 'GE'],
    'CSX': ['UNP', 'NSC'],
    'NSC': ['UNP', 'CSX'],
    'UNP': ['CSX', 'NSC'],
    'EFX': ['VRSK', 'LDOS'],
    'J': ['VRSK', 'EFX'],
    'LDOS': ['VRSK', 'EFX'],
    'VRSK': ['EFX', 'LDOS'],
    'FAST': ['URI', 'GWW'],
    'URI': ['GWW', 'FAST'],
    'GWW': ['URI', 'FAST'],
    'ADBE': ['PLTR', 'CRM'],
    'APP': ['PLTR', 'CRM'],
    'ADSK': ['PLTR', 'CRM'],
    'CDNS': ['PLTR', 'CRM'],
    'DDOG': ['PLTR', 'CRM'],
    'FICO': ['PLTR', 'CRM'],
    'INTU': ['PLTR', 'CRM'],
    'PLTR': ['CRM', 'APP'],
    'PTC': ['PLTR', 'CRM'],
    'ROP': ['PLTR', 'CRM'],
    'CRM': ['PLTR', 'APP'],
    'SNPS': ['PLTR', 'CRM'],
    'TRMB': ['PLTR', 'CRM'],
    'TYL': ['PLTR', 'CRM'],
    'WDAY': ['PLTR', 'CRM'],
    'ANET': ['CSCO', 'MSI'],
    'CIEN': ['CSCO', 'ANET'],
    'CSCO': ['ANET', 'MSI'],
    'FFIV': ['CSCO', 'ANET'],
    'LITE': ['CSCO', 'ANET'],
    'MSI': ['CSCO', 'ANET'],
    'APH': ['GLW', 'COHR'],
    'COHR': ['APH', 'GLW'],
    'GLW': ['APH', 'COHR'],
    'KEYS': ['TDY', 'ZBRA'],
    'TDY': ['KEYS', 'ZBRA'],
    'ZBRA': ['KEYS', 'TDY'],
    'FLEX': ['TEL', 'JBL'],
    'JBL': ['TEL', 'FLEX'],
    'TEL': ['FLEX', 'JBL'],
    'AKAM': ['VRSN', 'GDDY'],
    'GDDY': ['VRSN', 'AKAM'],
    'VRSN': ['AKAM', 'GDDY'],
    'ACN': ['IBM', 'CTSH'],
    'CTSH': ['IBM', 'ACN'],
    'IT': ['IBM', 'ACN'],
    'IBM': ['ACN', 'CTSH'],
    'AMAT': ['LRCX', 'KLAC'],
    'KLAC': ['AMAT', 'LRCX'],
    'LRCX': ['AMAT', 'KLAC'],
    'Q': ['AMAT', 'LRCX'],
    'TER': ['AMAT', 'LRCX'],
    'AMD': ['NVDA', 'AVGO'],
    'ADI': ['NVDA', 'AVGO'],
    'AVGO': ['NVDA', 'MU'],
    'FSLR': ['NVDA', 'AVGO'],
    'INTC': ['NVDA', 'AVGO'],
    'MRVL': ['NVDA', 'AVGO'],
    'MCHP': ['NVDA', 'AVGO'],
    'MU': ['NVDA', 'AVGO'],
    'MPWR': ['NVDA', 'AVGO'],
    'NVDA': ['AVGO', 'MU'],
    'NXPI': ['NVDA', 'AVGO'],
    'ON': ['NVDA', 'AVGO'],
    'QCOM': ['NVDA', 'AVGO'],
    'SWKS': ['NVDA', 'AVGO'],
    'TXN': ['NVDA', 'AVGO'],
    'CRWD': ['MSFT', 'ORCL'],
    'FTNT': ['MSFT', 'ORCL'],
    'GEN': ['MSFT', 'ORCL'],
    'MSFT': ['ORCL', 'PANW'],
    'ORCL': ['MSFT', 'PANW'],
    'PANW': ['MSFT', 'ORCL'],
    'NOW': ['MSFT', 'ORCL'],
    'CDW': ['NVDA', 'AAPL'],
    'AAPL': ['DELL', 'SNDK'],
    'DELL': ['AAPL', 'SNDK'],
    'HPE': ['AAPL', 'DELL'],
    'HPQ': ['AAPL', 'DELL'],
    'NTAP': ['AAPL', 'DELL'],
    'SNDK': ['AAPL', 'DELL'],
    'STX': ['AAPL', 'DELL'],
    'SMCI': ['AAPL', 'DELL'],
    'WDC': ['AAPL', 'DELL'],
    'DOW': ['LYB'],
    'LYB': ['DOW'],
    'CRH': ['VMC', 'MLM'],
    'MLM': ['CRH', 'VMC'],
    'VMC': ['CRH', 'MLM'],
    'FCX': ['LIN', 'NEM'],
    'CF': ['CTVA', 'MOS'],
    'CTVA': ['CF', 'MOS'],
    'MOS': ['CTVA', 'CF'],
    'NEM': ['LIN', 'FCX'],
    'APD': ['LIN'],
    'LIN': ['APD'],
    'BALL': ['LIN', 'FCX'],
    'AMCR': ['SW', 'IP'],
    'AVY': ['SW', 'AMCR'],
    'IP': ['SW', 'AMCR'],
    'PKG': ['SW', 'AMCR'],
    'SW': ['AMCR', 'IP'],
    'ALB': ['SHW', 'ECL'],
    'DD': ['SHW', 'ECL'],
    'ECL': ['SHW', 'PPG'],
    'IFF': ['SHW', 'ECL'],
    'PPG': ['SHW', 'ECL'],
    'SHW': ['ECL', 'PPG'],
    'NUE': ['STLD'],
    'STLD': ['NUE'],
    'DLR': ['EQIX'],
    'EQIX': ['DLR'],
    'ARE': ['WELL', 'VTR'],
    'DOC': ['WELL', 'VTR'],
    'VTR': ['WELL', 'DOC'],
    'WELL': ['VTR', 'DOC'],
    'HST': ['WELL', 'PLD'],
    'PLD': ['WELL', 'AMT'],
    'AVB': ['EQR', 'ESS'],
    'CPT': ['AVB', 'EQR'],
    'EQR': ['AVB', 'ESS'],
    'ESS': ['AVB', 'EQR'],
    'MAA': ['AVB', 'EQR'],
    'UDR': ['AVB', 'EQR'],
    'BXP': ['WELL', 'PLD'],
    'IRM': ['VICI'],
    'VICI': ['IRM'],
    'CBRE': ['CSGP'],
    'CSGP': ['CBRE'],
    'FRT': ['SPG', 'O'],
    'KIM': ['SPG', 'O'],
    'O': ['SPG', 'KIM'],
    'REG': ['SPG', 'O'],
    'SPG': ['O', 'KIM'],
    'EXR': ['PSA'],
    'PSA': ['EXR'],
    'INVH': ['WELL', 'PLD'],
    'AMT': ['CCI', 'SBAC'],
    'CCI': ['AMT', 'SBAC'],
    'SBAC': ['AMT', 'CCI'],
    'WY': ['WELL', 'PLD'],
    'LNT': ['NEE', 'DUK'],
    'AEP': ['NEE', 'DUK'],
    'CEG': ['NEE', 'DUK'],
    'DUK': ['NEE', 'SO'],
    'EIX': ['NEE', 'DUK'],
    'ETR': ['NEE', 'DUK'],
    'EVRG': ['NEE', 'DUK'],
    'ES': ['NEE', 'DUK'],
    'EXC': ['NEE', 'DUK'],
    'FE': ['NEE', 'DUK'],
    'NEE': ['DUK', 'SO'],
    'NRG': ['NEE', 'DUK'],
    'PCG': ['NEE', 'DUK'],
    'PNW': ['NEE', 'DUK'],
    'PPL': ['NEE', 'DUK'],
    'SO': ['NEE', 'DUK'],
    'XEL': ['NEE', 'DUK'],
    'ATO': ['NEE', 'DUK'],
    'AES': ['VST'],
    'VST': ['AES'],
    'AEE': ['D', 'SRE'],
    'CNP': ['D', 'SRE'],
    'CMS': ['D', 'SRE'],
    'ED': ['D', 'SRE'],
    'D': ['SRE', 'ED'],
    'DTE': ['D', 'SRE'],
    'NI': ['D', 'SRE'],
    'PEG': ['D', 'SRE'],
    'SRE': ['D', 'ED'],
    'WEC': ['D', 'SRE'],
    'AWK': ['NEE', 'DUK']
}
