"""Dictionary mapping stock tickers to biggest competitors within the same industry/sector."""

competitor_map = {
            'OMC': ['IPG'],          
            'IPG': ['OMC'],
            'FOXA': ['PARA'],
            'PARA': ['FOXA'],
            'CHTR': ['CMSCA', 'T'],        
            'CMSCA': ['CHTR', 'T'],
            'T': ['VZ', 'CMSCA'],           
            'VZ': ['T', 'CMSCA'],
            'EA': ['TTWO', 'META'],        
            'TTWO': ['EA', 'META'],
            'GOOGL': ['META', 'MTCH'],
            'META': ['GOOGL', 'MTCH'],
            'MTCH': ['GOOGL', 'META'],
            'LYV': ['NFLX', 'DIS'],
            'NFLX': ['DIS', 'LYV'],
            'DIS': ['NFLX', 'LYV'],
            'TKO': ['WBD', 'LYV'],
            'WBD': ['TKO', 'LYV'],
            'NWSA': ['PARA', 'CMSCA'],         
            'TMUS': ['T', 'VZ'],            
            'ROST': ['TJX'],         
            'TJX': ['ROST'],
            'LULU': ['RL', 'TPR'],
            'RL': ['LULU', 'TPR'],
            'TPR': ['LULU', 'RL'],
            'F': ['GM', 'TSLA'],
            'GM': ['TSLA', 'F'],
            'TSLA': ['GM', 'F'],
            'APTV': ['TEL', 'LKQ'],            
            'AZO': ['ORLY', 'KMX'],
            'KMX': ['ORLY', 'AZO'],
            'ORLY': ['AZO', 'KMX'],
            'AMZN': ['WMT', 'TGT'],         
            'EBAY': ['AMZN', 'META'],
            'CZR': ['LVS', 'MGM'],
            'LVS': ['MGM', 'CZR'],
            'MGM': ['LVS', 'CZR'],
            'WYNN': ['LVS', 'MGM'],
            'BBY': ['AMZN', 'EBAY'],        
            'GRMN': ['AAPL', 'TXT'],         
            'GPC': ['LKQ', 'POOL'],
            'LKQ': ['GPC', 'POOL'],
            'POOL': ['GPC', 'LKQ'],
            'DECK': ['NKE'],           
            'NKE': ['DECK'],
            'MHK': ['HD'],
            'LOW': ['HD'],
            'HD': ['LOW'],
            'DHI': ['LEN', 'NVR'],
            'LEN': ['DHI', 'NVR'],
            'NVR': ['DHI', 'LEN'],
            'PHM': ['DHI', 'LEN'],
            'WSM': ['HD'],
            'ABNB': ['BKNG', 'MAR'],
            'BKNG': ['ABNB', 'MAR'],
            'CCL': ['BKNG', 'ABNB'],
            'EXPE': ['BKNG', 'ABNB'],
            'HLT': ['BKNG', 'ABNB'],
            'MAR': ['BKNG', 'ABNB'],
            'NCLH': ['BKNG', 'ABNB'],
            'RCL': ['BKNG', 'ABNB'],
            'HAS': ['DIS'],
            'TSCO': ['ULTA'],
            'ULTA': ['TSCO'],
            'CMG': ['MCD', 'SBUX'],
            'DRI': ['MCD', 'SBUX'],
            'DPZ': ['MCD', 'SBUX'],
            'DASH': ['MCD', 'SBUX'],
            'MCD': ['SBUX', 'DASH'],
            'SBUX': ['MCD', 'DASH'],
            'YUM': ['MCD', 'SBUX'],
            'ADM': ['BG'],
            'BG': ['ADM'],
            'TAP': ['STZ'],
            'COST': ['WMT', 'TGT'],
            'DG': ['WMT', 'COST'],
            'DLTR': ['WMT', 'COST'],
            'TGT': ['WMT', 'COST'],
            'WMT': ['COST', 'TGT'],
            'BF.B': ['STZ'],
            'STZ': ['BF.B'],
            'WBA': ['CVS'],
            'SYY': ['COST'],
            'KR': ['WMT'],
            'CHD': ['PG', 'CL'],
            'CL': ['PG', 'KMB'],
            'KMB': ['PG', 'CL'],
            'CLX': ['PG', 'CL'],
            'PG': ['CL', 'KMB'],
            'CAG': ['MDLZ', 'HSY'],
            'GIS': ['MDLZ', 'HSY'],
            'HRL': ['MDLZ', 'HSY'],
            'K': ['MDLZ', 'HSY'],
            'LW': ['MDLZ', 'HSY'],
            'MKC': ['MDLZ', 'HSY'],
            'MDLZ': ['HSY', 'KHC'],
            'CPB': ['MDLZ', 'HSY'],
            'HSY': ['MDLZ', 'KHC'],
            'SJM': ['MDLZ', 'HSY'],
            'KHC': ['MDLZ', 'HSY'],
            'TSN': ['MDLZ', 'HSY'],
            'KVUE': ['EL'],
            'EL': ['KVUE'],
            'KDP': ['KO', 'PEP'],
            'MNST': ['KO', 'PEP'],
            'PEP': ['KO', 'MNST'],
            'KO': ['PEP', 'MNST'],
            'MO': ['PM'],
            'PM': ['MO'],
            'CVX': ['XOM', 'OXY'],
            'XOM': ['CVX', 'OXY'],
            'OXY': ['XOM', 'CVX'],
            'BKR': ['SLB', 'HAL'],
            'HAL': ['SLB', 'BKR'],
            'SLB': ['BKR', 'HAL'],
            'APA': ['COP', 'EOG'],
            'COP': ['EOG', 'HES'],
            'CTRA': ['COP', 'EOG'],
            'DVN': ['COP', 'EOG'],
            'FANG': ['COP', 'EOG'],
            'EOG': ['COP', 'HES'],
            'EQT': ['COP', 'EOG'],
            'EXE': ['COP', 'EOG'],
            'HES': ['COP', 'EOG'],
            'TPL': ['COP', 'EOG'],
            'MPC': ['PSX', 'VLO'],
            'PSX': ['MPC', 'VLO'],
            'VLO': ['MPC', 'PSX'],
            'KMI': ['WMB', 'OKE'],
            'OKE': ['WMB', 'KMI'],
            'TRGP': ['WMB', 'KMI'],
            'WMB': ['KMI', 'OKE'],
            'AMP': ['BLK', 'KKR'],
            'BLK': ['KKR', 'BX'],
            'BX': ['BLK', 'KKR'],
            'BEN': ['BLK', 'KKR'],
            'IVZ': ['BLK', 'KKR'],
            'KKR': ['BLK', 'BX'],
            'NTRS': ['BLK', 'KKR'],
            'STT': ['BLK', 'KKR'],
            'TROW': ['BLK', 'KKR'],
            'BK': ['BLK', 'KKR'],
            'AXP': ['COF', 'SYF'],
            'COF': ['AXP', 'SYF'],
            'SYF': ['AXP', 'COF'],
            'BAC': ['JPM', 'WFC'],
            'C': ['JPM', 'BAC'],
            'FITB': ['JPM', 'BAC'],
            'JPM': ['BAC', 'WFC'],
            'KEY': ['JPM', 'BAC'],
            'PNC': ['JPM', 'BAC'],
            'USB': ['JPM', 'BAC'],
            'WFC': ['JPM', 'BAC'],
            'APO': ['BX'],
            'CBOE': ['SPGI', 'CME'],
            'CME': ['SPGI', 'ICE'],
            'COIN': ['SPGI', 'CME'],
            'FDS': ['SPGI', 'CME'],
            'ICE': ['SPGI', 'CME'],
            'MKTX': ['SPGI', 'CME'],
            'MCO': ['SPGI', 'CME'],
            'MSCI': ['SPGI', 'CME'],
            'NDAQ': ['SPGI', 'CME'],
            'SPGI': ['CME', 'ICE'],
            'AON': ['MMC', 'AJG'],
            'AJG': ['MMC', 'AON'],
            'BRO': ['MMC', 'AJG'],
            'MMC': ['AJG', 'AON'],
            'WTW': ['MMC', 'AJG'],
            'MS': ['GS', 'SCHW'],
            'RJF': ['MS', 'GS'],
            'SCHW': ['MS', 'GS'],
            'GS': ['MS', 'SCHW'],
            'AFL': ['MET', 'PRU'],
            'GL': ['AFL', 'MET'],
            'MET': ['AFL', 'PRU'],
            'PFG': ['AFL', 'MET'],
            'PRU': ['AFL', 'MET'],
            'BRK.A': ['BLK'],
            'AIG': ['PGR', 'CB'],
            'ACGL': ['PGR', 'CB'],
            'AIZ': ['PGR', 'CB'],
            'CB': ['PGR', 'TRV'],
            'CINF': ['PGR', 'CB'],
            'ERIE': ['PGR', 'CB'],
            'L': ['PGR', 'CB'],
            'ALL': ['PGR', 'CB'],
            'HIG': ['PGR', 'CB'],
            'PGR': ['CB', 'TRV'],
            'TRV': ['PGR', 'CB'],
            'WRB': ['PGR', 'CB'],
            'CFG': ['TFC', 'MTB'],
            'HBAN': ['TFC', 'MTB'],
            'MTB': ['TFC', 'HBAN'],
            'RF': ['TFC', 'MTB'],
            'TFC': ['MTB', 'HBAN'],
            'EG': ['AIG'],
            'CPAY': ['V', 'MA'],
            'FIS': ['V', 'MA'],
            'FI': ['V', 'MA'],
            'GPN': ['V', 'MA'],
            'JKHY': ['V', 'MA'],
            'MA': ['V', 'FI'],
            'PYPL': ['V', 'MA'],
            'V': ['MA', 'FI'],
            'ABBV': ['AMGN', 'GILD'],
            'AMGN': ['ABBV', 'GILD'],
            'BIIB': ['ABBV', 'AMGN'],
            'GILD': ['ABBV', 'AMGN'],
            'INCY': ['ABBV', 'AMGN'],
            'MRNA': ['ABBV', 'AMGN'],
            'REGN': ['ABBV', 'AMGN'],
            'VRTX': ['ABBV', 'AMGN'],
            'CAH': ['MCK', 'COR'],
            'COR': ['MCK', 'CAH'],
            'HSIC': ['MCK', 'COR'],
            'MCK': ['COR', 'CAH'],
            'ABT': ['ISRG', 'BSX'],
            'BAX': ['ABT', 'ISRG'],
            'BDX': ['ABT', 'ISRG'],
            'BSX': ['ABT', 'ISRG'],
            'DXCM': ['ABT', 'ISRG'],
            'EW': ['ABT', 'ISRG'],
            'GEHC': ['ABT', 'ISRG'],
            'HOLX': ['ABT', 'ISRG'],
            'IDXX': ['ABT', 'ISRG'],
            'PODD': ['ABT', 'ISRG'],
            'ISRG': ['ABT', 'BSX'],
            'MDT': ['ABT', 'ISRG'],
            'RMD': ['ABT', 'ISRG'],
            'STE': ['ABT', 'ISRG'],
            'SYK': ['ABT', 'ISRG'],
            'ZBH': ['ABT', 'ISRG'],
            'HCA': ['UHS'],
            'UHS': ['HCA'],
            'CVS': ['CI', 'LH'],
            'DVA': ['CI', 'CVS'],
            'LH': ['CI', 'CVS'],
            'DGX': ['CI', 'CVS'],
            'CI': ['CVS', 'LH'],
            'ALGN': ['COO', 'SOLV'],
            'SOLV': ['COO', 'ALGN'],
            'COO': ['ALGN', 'SOLV'],
            'A': ['TMO', 'DHR'],
            'TECH': ['TMO', 'DHR'],
            'CRL': ['TMO', 'DHR'],
            'DHR': ['TMO', 'A'],
            'IQV': ['TMO', 'DHR'],
            'MTD': ['TMO', 'DHR'],
            'RVTY': ['TMO', 'DHR'],
            'TMO': ['DHR', 'A'],
            'WAT': ['TMO', 'DHR'],
            'WST': ['TMO', 'DHR'],
            'CNC': ['UNH', 'ELV'],
            'ELV': ['UNH', 'HUM'],
            'HUM': ['UNH', 'ELV'],
            'MOH': ['UNH', 'ELV'],
            'UNH': ['ELV', 'HUM'],
            'BMY': ['LLY', 'JNJ'],
            'LLY': ['JNJ', 'MRK'],
            'JNJ': ['LLY', 'MRK'],
            'MRK': ['LLY', 'JNJ'],
            'PFE': ['LLY', 'JNJ'],
            'VTRS': ['LLY', 'JNJ'],
            'ZTS': ['LLY', 'JNJ'],
            'AXON': ['GE', 'RTX'],
            'GD': ['GE', 'RTX'],
            'GE': ['RTX', 'BA'],
            'HWM': ['GE', 'RTX'],
            'HII': ['GE', 'RTX'],
            'LHX': ['GE', 'RTX'],
            'LMT': ['GE', 'RTX'],
            'NOC': ['GE', 'RTX'],
            'RTX': ['GE', 'BA'],
            'TXT': ['GE', 'RTX'],
            'BA': ['GE', 'RTX'],
            'TDG': ['GE', 'RTX'],
            'DE': ['CAT'],
            'CHRW': ['UPS', 'FDX'],
            'EXPD': ['UPS', 'FDX'],
            'FDX': ['UPS', 'EXPD'],
            'UPS': ['FDX', 'EXPD'],
            'AOS': ['TT', 'JCI'],
            'ALLE': ['TT', 'JCI'],
            'BLDR': ['TT', 'JCI'],
            'CARR': ['TT', 'JCI'],
            'JCI': ['TT', 'CARR'],
            'LII': ['TT', 'JCI'],
            'MAS': ['TT', 'JCI'],
            'TT': ['JCI', 'CARR'],
            'JBHT': ['ODFL'],
            'ODFL': ['JBHT'],
            'PWR': ['J'],
            'CAT': ['PCAR', 'CMI'],
            'CMI': ['CAT', 'PCAR'],
            'PCAR': ['CAT', 'CMI'],
            'WAB': ['CAT', 'PCAR'],
            'BR': ['FIS'],
            'CTAS': ['CPRT'],
            'CPRT': ['CTAS'],
            'AME': ['ETN', 'EMR'],
            'ETN': ['EMR', 'AME'],
            'EMR': ['ETN', 'AME'],
            'GNRC': ['ETN', 'EMR'],
            'HUBB': ['ETN', 'EMR'],
            'ROK': ['ETN', 'EMR'],
            'RSG': ['WM', 'ROL'],
            'ROL': ['WM', 'RSG'],
            'VLTO': ['WM', 'RSG'],
            'WM': ['RSG', 'ROL'],
            'GEV': ['NEE'],
            'ADP': ['PAYX', 'PAYC'],
            'DAY': ['ADP', 'PAYX'],
            'PAYX': ['ADP', 'PAYC'],
            'PAYC': ['ADP', 'PAYX'],
            'MMM': ['HON'],
            'HON': ['MMM'],
            'DOV': ['PH', 'ITW'],
            'FTV': ['PH', 'ITW'],
            'IEX': ['PH', 'ITW'],
            'ITW': ['PH', 'OTIS'],
            'IR': ['PH', 'ITW'],
            'NDSN': ['PH', 'ITW'],
            'OTIS': ['PH', 'ITW'],
            'PH': ['ITW', 'OTIS'],
            'PNR': ['PH', 'ITW'],
            'SNA': ['PH', 'ITW'],
            'SWK': ['PH', 'ITW'],
            'XYL': ['PH', 'ITW'],
            'DAL': ['UAL', 'LUV'],
            'LUV': ['DAL', 'UAL'],
            'UAL': ['DAL', 'LUV'],
            'UBER': ['DASH'],
            'CSX': ['UNP', 'NSC'],
            'NSC': ['UNP', 'CSX'],
            'UNP': ['CSX', 'NSC'],
            'EFX': ['VRSK', 'LDOS'],
            'J': ['VRSK', 'EFX'],
            'LDOS': ['VRSK', 'EFX'],
            'VRSK': ['EFX', 'LDOS'],
            'FAST': ['GWW', 'URI'],
            'URI': ['GWW', 'FAST'],
            'GWW': ['FAST', 'URI'],
            'ADBE': ['PLTR', 'CRM'],
            'ANSS': ['PLTR', 'CRM'],
            'ADSK': ['PLTR', 'CRM'],
            'CDNS': ['PLTR', 'CRM'],
            'FICO': ['PLTR', 'CRM'],
            'INTU': ['PLTR', 'CRM'],
            'PLTR': ['CRM', 'INTU'],
            'PTC': ['PLTR', 'CRM'],
            'ROP': ['PLTR', 'CRM'],
            'CRM': ['PLTR', 'INTU'],
            'SNPS': ['PLTR', 'CRM'],
            'TYL': ['PLTR', 'CRM'],
            'WDAY': ['PLTR', 'CRM'],
            'ANET': ['CSCO', 'MSI'],
            'CSCO': ['ANET', 'MSI'],
            'FFIV': ['CSCO', 'ANET'],
            'JNPR': ['CSCO', 'ANET'],
            'MSI': ['CSCO', 'ANET'],
            'APH': ['GLW'],
            'GLW': ['APH'],
            'KEYS': ['TDY', 'TRMB'],
            'TDY': ['KEYS', 'TRMB'],
            'TRMB': ['KEYS', 'TDY'],
            'ZBRA': ['KEYS', 'TDY'],
            'JBL': ['TEL'],
            'TEL': ['JBL'],
            'AKAM': ['GDDY', 'VRSN'],
            'GDDY': ['VRSN', 'AKAM'],
            'VRSN': ['GDDY', 'AKAM'],
            'ACN': ['IBM', 'CTSH'],
            'CTSH': ['IBM', 'ACN'],
            'EPAM': ['IBM', 'ACN'],
            'IT': ['IBM', 'ACN'],
            'IBM': ['ACN', 'CTSH'],
            'AMAT': ['LRCX', 'KLAC'],
            'ENPH': ['AMAT', 'LRCX'],
            'KLAC': ['AMAT', 'LRCX'],
            'LRCX': ['AMAT', 'KLAC'],
            'TER': ['AMAT', 'LRCX'],
            'AMD': ['NVDA', 'AVGO'],
            'ADI': ['NVDA', 'AVGO'],
            'AVGO': ['NVDA', 'AMD'],
            'FSLR': ['NVDA', 'AVGO'],
            'INTC': ['NVDA', 'AVGO'],
            'MCHP': ['NVDA', 'AVGO'],
            'MU': ['NVDA', 'AVGO'],
            'MPWR': ['NVDA', 'AVGO'],
            'NVDA': ['AVGO', 'AMD'],
            'NXPI': ['NVDA', 'AVGO'],
            'ON': ['NVDA', 'AVGO'],
            'QCOM': ['NVDA', 'AVGO'],
            'SWKS': ['NVDA', 'AVGO'],
            'TXN': ['NVDA', 'AVGO'],
            'CRWD': ['MSFT', 'ORCL'],
            'FTNT': ['MSFT', 'ORCL'],
            'GEN': ['MSFT', 'ORCL'],
            'MSFT': ['ORCL', 'NOW'],
            'ORCL': ['MSFT', 'NOW'],
            'PANW': ['MSFT', 'ORCL'],
            'NOW': ['MSFT', 'ORCL'],
            'CDW': ['ACN'],
            'AAPL': ['DELL', 'STX'],
            'DELL': ['AAPL', 'STX'],
            'HPE': ['AAPL', 'DELL'],
            'HPQ': ['AAPL', 'DELL'],
            'NTAP': ['AAPL', 'DELL'],
            'STX': ['AAPL', 'DELL'],
            'SMCI': ['AAPL', 'DELL'],
            'WDC': ['AAPL', 'DELL'],
            "DOW": ["LYB"],
            "LYB": ["DOW"],
            "MLM": ["VMC"],
            "VMC": ["MLM"],
            "FCX": ['NEM'],
            "CF": ["CTVA", "MOS"],
            "CTVA": ["CF", "MOS"],
            "MOS": ["CTVA", "CF"],
            "NEM": ["FCX"],
            "APD": ["LIN"],
            "LIN": ["APD"],
            "BALL": ['AMCR'],
            "AMCR": ["IP", "SW"],
            "AVY": ["IP", "SW"],
            "IP": ["SW", "AMCR"],
            "PKG": ["IP", "SW"],
            "SW": ["IP", "AMCR"],
            "ALB": ["SHW", "ECL"],
            "DD": ["SHW", "ECL"],
            "EMN": ["SHW", "ECL"],
            "ECL": ["SHW", "DD"],
            "IFF": ["SHW", "ECL"],
            "PPG": ["SHW", "ECL"],
            "SHW": ["ECL", "DD"],
            "NUE": ["STLD"],
            "STLD": ["NUE"],
            "DLR": ["EQIX"],
            "EQIX": ["DLR"],
            "ARE": ["WELL", "VTR"],
            "DOC": ["WELL", "VTR"],
            "VTR": ["WELL", "ARE"],
            "WELL": ["VTR", "ARE"],
            "HST": ['DOC'],
            "PLD": ['EQIX'],
            "AVB": ["EQR", "ESS"],
            "CPT": ["AVB", "EQR"],
            "EQR": ["AVB", "ESS"],
            "ESS": ["AVB", "EQR"],
            "MAA": ["AVB", "EQR"],
            "UDR": ["AVB", "EQR"],
            "BXP": ["ARE"],
            "IRM": ["VICI"],
            "VICI": ["IRM"],
            "CBRE": ["CSGP"],
            "CSGP": ["CBRE"],
            "FRT": ["O", "SPG"],
            "KIM": ["O", "SPG"],
            "O": ["SPG", "KIM"],
            "REG": ["O", "SPG"],
            "SPG": ["O", "KIM"],
            "EXR": ["PSA"],
            "PSA": ["EXR"],
            "INVH": ['MAA'],
            "AMT": ["CCI", "SBAC"],
            "CCI": ["AMT", "SBAC"],
            "SBAC": ["AMT", "CCI"],
            "WY": ['PLD'],
            "LNT": ["NEE", "SO"],
            "AEP": ["NEE", "SO"],
            "CEG": ["NEE", "SO"],
            "DUK": ["NEE", "SO"],
            "EIX": ["NEE", "SO"],
            "ETR": ["NEE", "SO"],
            "EVRG": ["NEE", "SO"],
            "ES": ["NEE", "SO"],
            "EXC": ["NEE", "SO"],
            "FE": ["NEE", "SO"],
            "NEE": ["SO", "CEG"],
            "NRG": ["NEE", "SO"],
            "PCG": ["NEE", "SO"],
            "PNW": ["NEE", "SO"],
            "PPL": ["NEE", "SO"],
            "SO": ["NEE", "CEG"],
            "XEL": ["NEE", "SO"],
            "ATO": ['NEE'],
            "AES": ["VST"],
            "VST": ["AES"],
            "AEE": ["SRE", "D"],
            "CNP": ["SRE", "D"],
            "CMS": ["SRE", "D"],
            "ED": ["SRE", "D"],
            "D": ["SRE", "PEG"],
            "DTE": ["SRE", "D"],
            "NI": ["SRE", "D"],
            "PEG": ["SRE", "D"],
            "SRE": ["D", "PEG"],
            "WEC": ["SRE", "D"],
            "AWK": ["NEE"]
}




